// Generated by Wrangler on Sat Mar 15 2025 01:10:18 GMT+0000 (GMT)
// by running `wrangler types`

interface Env {
	gdglearning: KVNamespace;
	MY_VARIABLE: "production_value";
	SMTP_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	HST_PASSWORD: string;
	CLOUDFLARE_EMAIL: string;
	CLOUDFLARE_APIKEY: string;
	DB: D1Database;
}
